---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-odh-monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.corp.redhat.com:25'
      smtp_from: 'AlertManager-Production@redhat.com'
      smtp_auth_username: 'alertmanager'
      smtp_auth_password: 'password'
      smtp_require_tls: false

    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'github-receiver-issues'

    receivers:
    - name: 'webhook'
      webhook_configs:
        - url: 'http://alertmanagerwh:30500/'

    - name: 'developer-mails'
      email_configs:
        - to: 'hveeradh@redhat.com'
          send_resolved: true

    - name: 'github-receiver-issues'
      webhook_configs:
        - url: 'http://localhost:9393/v1/receiver'
