---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-odh-monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.corp.redhat.com:25'
      smtp_from: 'AlertManager-Production@redhat.com'
      smtp_auth_username: 'alertmanager'
      smtp_auth_password: 'password'
      smtp_require_tls: false

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'github-receiver-issues'

    routes:
    - match_re:
        alertname: DeadManSwitch
      receiver: deadman-switch
      repeat_interval: 5m

    receivers:
    - name: 'developer-mails'
      email_configs:
        - to: 'hveeradh@redhat.com'
          send_resolved: true

    - name: 'github-receiver-issues'
      webhook_configs:
        - url: 'http://github-receiver-service.opf-monitoring.svc.cluster.local:9393/v1/receiver'

    - name: 'deadman-switch'
      webhook_configs:
        - url: 'https://nosnch.in/b7cd961fad?m=just+checking+in'
          send_resolved: false
