---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
    name: grafana
spec:
    baseImage: quay.io/app-sre/grafana:7.1.1
    client:
        preferService: true
    config:
        auth.anonymous:
            enabled: true
        log:
            level: warn
            mode: console
        security:
          admin_user: root
          admin_password: secret
        auth:
          disable_login_form: false
          disable_signout_menu: true
        auth.basic:
          enabled: true
    dashboardLabelSelector:
    -   matchExpressions:
        -   key: app
            operator: In
            values:
            - grafana
    ingress:
        enabled: true
