---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: odh-monitoring
spec:
  groups:
    - name: OperateFirst
      rules:
        - alert: JupyterHub Service Down
          expr: up{service="jupyterhub"} == 0
          for: 1m
          annotations:
            summary: "JupyterHub is no longer available"
            severity: "HIGH"
