---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: odh-monitoring
spec:
  groups:
    - name: OperateFirst
      rules:
        - alert: Service Down
          expr: up{service="prometheus-operated"} == 1
          for: 1m
          annotations:
            summary: "Service is no longer available"
            severity: "HIGH"
    - name: DeadManSwitch
      interval: 1m
      rules:
        - alert: DeadManSwitch
          expr: vector(1)
          labels:
            severity: critical
          annotations:
            description: This is a DeadManSwitch meant to ensure that the entire Alerting pipeline is functional
            summary: "Alerting DeadMansSwitch"
