---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: odh-monitoring
  labels:
    app: prometheus
    prometheus: k8s
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-operated
        namespace: opf-monitoring
        port: web
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      prometheus: k8s
  serviceMonitorNamespaceSelector:
    matchLabels: {}
  podMonitorSelector:
    matchLabels:
      prometheus: k8s
  podMonitorNamespaceSelector:
    matchLabels: {}
  securityContext: {}
  ruleNamespaceSelector:
    matchLabels: {}
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: k8s
  replicas: 2
  remoteRead:
    - url: "http://prometheus-operated.opf-jupyterhub.svc.cluster.local:9090\
            /api/v1/read"
