---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: odh-monitoring
  labels:
    app: prometheus
    prometheus: k8s
spec:
  alerting:
    alertmanagers:
      - name: odh-monitoring
        namespace: opf-monitoring
        port: web
  serviceMonitorSelector: {}
  securityContext: {}
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: k8s
  replicas: 2
  remoteRead:
    - url: "http://prometheus-operated.opf-jupyterhub.svc.cluster.local:9090\
            /api/v1/read"
