---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-prober
  labels:
    app: blackbox-prober
spec:
  selector:
    matchLabels:
      app: blackbox-prober
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-prober
    spec:
      containers:
      - name: blackbox-prober
        args:
        - --config.file=/etc/config/blackbox-prober-config.yaml
        - --log.level=debug
        image: quay.io/prometheus/blackbox-exporter:v0.19.0
        volumeMounts:
        - name: config
          mountPath: /etc/config/
        - name: es-cert
          mountPath: /cert
        - name: es-key
          mountPath: /key
      volumes:
      - name: config
        configMap:
          name: blackbox-prober-config
      - name: es-cert
        secret:
          secretName: es-crt
      - name: es-key
        secret:
          secretName: es-key
