modules:
  http_2xx:
    prober: http
    timeout: 30s
    http:
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208]
      preferred_ip_protocol: "ip4"
  http_es:
    prober: http
    http:
      tls_config:
        cert_file: /cert/es-secret.enc.yaml
        key_file: /key/es-secret.enc.yaml
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"
  tcp_ingest:
    prober: tcp
    timeout: 10s
    http:
      preferred_ip_protocol: "ip4"
