---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-monitoring
resources:
  - blackbox.yaml
  - blackbox-service.yaml
  - es-secret-generator.yaml
  - probe.yaml
configMapGenerator:
  - name: blackbox-prober-config
    files:
    - blackbox-prober-config.yaml
generatorOptions:
  disableNameSuffixHash: true
