---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: opf-prober
spec:
  jobName: opf-status
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-prober.opf-monitoring.svc.cluster.local:80
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
      - https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/
      - http://argo-server-opf-argo.apps.zero.massopen.cloud/
      - http://superset-opf-superset.apps.zero.massopen.cloud/
      - https://hue-opf-datacatalog.apps.zero.massopen.cloud/desktop/debug/is_alive
      - http://thriftserver-opf-datacatalog.apps.zero.massopen.cloud/
      - https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/
      - https://kibana-openshift-logging.apps.zero.massopen.cloud/api/status
      - https://elasticsearch-openshift-logging.apps.zero.massopen.cloud/
      - http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/
      relabelingConfigs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-prober.opf-monitoring.svc.cluster.local:80
      - regex: 'namespace'
        action: labeldrop
